language: perl6

perl6:
    - '2018.01'

install:
    - rakudobrew build-zef
    - zef --debug --deps-only install .

services:
  - postgresql: "9.6"

before_script:
  - psql -c 'create database agrammon_dev;' -U postgres
