### we install our own Rakudo below
# language: perl6
# perl6:
#     - '2018.01'
###
### Update RAKUDO_PKG_URL to the latest version available.
###
### https://github.com/nxadm/rakudo-pkg/releases
env:
  global:
    - TMPDIR=/tmp
    - RAKUDO_PKG_URL=https://github.com/nxadm/rakudo-pkg/releases/download/v2020.05.1/rakudo-pkg-Ubuntu20.04_2020.05.1-01_amd64.deb
    - PGPORT=5433

# cache precompiled modules
cache:
  directories:
  - $HOME/.perl6

services:
  - postgresql

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
  
before_script:
  - psql --command='create database agrammon_test'
  - psql --dbname=agrammon_test --command='create extension pgcrypto'

script:
    PERL6LIB=lib prove -v -r --exec=perl6 t/ xt/

# https://stackoverflow.com/questions/61734368/postgresql-12-on-travis-ci-taking-5-minutes-to-startup
# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-without-an-APT-Repository
before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - cd ${TMPDIR}
  - wget -O rakudo-pkg.deb ${RAKUDO_PKG_URL}
  - sudo dpkg -i rakudo-pkg.deb
  - cd ${TRAVIS_BUILD_DIR}
  - export PATH=$PATH:~/.perl6/bin:/opt/rakudo-pkg/bin
  - /opt/rakudo-pkg/bin/install-zef-as-user

install:
  - zef --debug --/test --deps-only install .
