name: All Tests

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

env:
  TMPDIR_PATH: /tmp
  POSTGRES_USER: postgres
  POSTGRES_HOST: localhost
  RAKU_VERSION: 2020.01

jobs:

  build:

    strategy:
        matrix:
            os:
                - ubuntu-16.04
                # - macos-latest

            raku:
                - '2019.07.1'
#                - '2020.01'

        fail-fast: false

    name: Raku ${{ matrix.raku }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    # The service containers will uses host port binding instead of container
    # networking so you access them via localhost rather than the service name
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

    - name: Checkout
      uses: actions/checkout@v1     

    - name: Create Agrammon DB
      run:
          psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -c 'create database agrammon_test' && psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER --dbname=agrammon_test -c 'create extension pgcrypto'
      env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port

    - name: Raku cache
      id: raku-cache
      uses: actions/cache@v1
      with:
          path: /opt/rakudo-pkg
          key: ${{ matrix.os }}-raku-${{ matrix.raku }}

    - name: Install Rakudo ${{ matrix.raku }} package
      if: steps.raku-cache.outputs.cache-hit != 'true'
      run: cd $TMPDIR && wget -O rakudo-pkg.deb `echo $RAKUDO_PKG_URL | sed -e 's/ubuntu-/Ubuntu/'` && sudo dpkg -i rakudo-pkg.deb && /opt/rakudo-pkg/bin/raku -v
      env:
          RAKUDO_PKG_URL: https://github.com/nxadm/rakudo-pkg/releases/download/v${{ matrix.raku}}/rakudo-pkg-${{ matrix.os }}_${{ matrix.raku }}-01_amd64.deb

    # don't depend on PATH setting
    - name: Patch zef path
      if: steps.raku-cache.outputs.cache-hit != 'true'
      run: sudo sed -i -e 's|/usr/bin/env perl6|/opt/rakudo-pkg/bin/raku|' /opt/rakudo-pkg/bin/zef && cat /opt/rakudo-pkg/bin/zef

    - name: Agrammon module cache
      id: agrammon-cache
      uses: actions/cache@v1
      with:
          path: /home/runner/.raku
          key: ${{ matrix.os }}-agrammon-${{ matrix.raku}}-${{ hashFiles('META6.json') }}

    - name: Zef store cache
      id: zef-cache
      uses: actions/cache@v1
      with:
          path: /home/runner/.zef/store
          key: ${{ matrix.os }}-zef-${{ matrix.raku}}-${{ hashFiles('META6.json') }}

    - name: Install raku modules
      if: steps.agrammon-cache.outputs.cache-hit != 'true' && steps.zef-cache.outputs.cache-hit != 'true'
      run: mkdir -p /home/runner/.raku && /opt/rakudo-pkg/bin/zef --debug --/test --deps-only --install-to=/home/runner/.raku install .

#    - name: Raku install dir
#      run: /opt/rakudo-pkg/bin/zef locate DB::Pg

    - name: Run tests
      run: /usr/bin/prove -v -r --exec="/opt/rakudo-pkg/bin/raku -Iinst#$HOME/.raku" xt/ t/user.t
      env:
          PERL6LIB: lib
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
