on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
# Runs all steps on the VM
# The service containers will use host port binding instead of container
# networking so you access them via localhost rather than the service name
  vm-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1     

    - name: Cache
      id: raku-cache
      uses: actions/cache@v1
      with:
        path: /opt/rakudo-pkg
        key: ${{ matrix.os }}-raku-modules-${{ hashFiles('META6.json') }}

    - name: Update keys
      if: steps.raku-cache.outputs.cache-hit != 'true'
      run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
    - name: Update source list
      if: steps.raku-cache.outputs.cache-hit != 'true'
      run: echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list.d/rakudo-pkg.list
    - name: Install Raku
      if: steps.raku-cache.outputs.cache-hit != 'true'
      run: sudo apt-get update && sudo apt-get install rakudo-pkg
    - name: Fix zef
      if: steps.raku-cache.outputs.cache-hit != 'true'
      run: sudo sed -i -e 's|/usr/bin/env perl6|/opt/rakudo-pkg/bin/raku|' /opt/rakudo-pkg/bin/zef && cat /opt/rakudo-pkg/bin/zef

#    - name: Cache
#      id: raku-module-cache
#      uses: actions/cache@v1
#      with:
#        path: /home/runner/.raku
#        key: ${{ matrix.os }}-raku-${{ hashFiles('META6.json') }}

    - name: Install Raku modules
      if: steps.raku-cache.outputs.cache-hit != 'true'
      run: /opt/rakudo-pkg/bin/zef --debug --/test --deps-only install .

    - name: Raku path
      run: /opt/rakudo-pkg/bin/zef locate DB::Pg

    - name: Run tests
      run: /usr/bin/prove -v -r --exec=/opt/rakudo-pkg/bin/raku xt/
      env:
        PERL6LIB: lib
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
