on:
  push:
#    branches:
#    - master
    paths-ignore:
    - '**.md'
  pull_request:
#    branches:
#    - master
    paths-ignore:
    - '**.md'

jobs:
# Runs all steps on the VM
# The service containers will use host port binding instead of container
# networking so you access them via localhost rather than the service name
  vm-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1     
    - name: Who am i
      run: whoami && pwd
    - name: Touching
      run: sudo touch TEST && ls -l
    - name: Create sources dir
      run: sudo mkdir -p /etc/apt/sources.list.d && sudo ls -ld /etc/apt/sources.list.d
    - name: Update keys
      run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
    - name: Update source list
      run: echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list.d/rakudo-pkg.list
    - name: Install Raku
      run: sudo apt-get update && sudo apt-get install rakudo-pkg
    - name: Fix zef
      run: sudo sed -i -e 's|/usr/bin/env perl6|/opt/rakudo-pkg/bin/raku|' /opt/rakudo-pkg/bin/zef && cat /opt/rakudo-pkg/bin/zef
    - name: Install Raku modules
      run: /opt/rakudo-pkg/bin/zef --debug --/test --deps-only install .
    - name: Run tests
      run: prove -v -r --exec=raku t/ xt/
      env:
        PERL6LIB: lib
        PATH: /opt/rakudo-pkg/bin
