on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Agrammon6
    steps:
    # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
    - name: Hello world
      uses: actions/hello-world-javascript-action@v1
      with:
      who-to-greet: 'Mona the Octocat'
      id: hello
    # This step prints an output (time) from the previous step's action.
    - name: Echo the greeting's time
      run: echo 'The time was ${{ steps.hello.outputs.time }}.'

#    - name: Checkout
#      uses: actions/checkout@v1
    # run raku tests
#   - name: Run tests
#        id: tests
#        uses: oposs/raku-container-action@master
