#on:
#  push:
#    paths-ignore:
#      - '**.md'
#  pull_request:
#    paths-ignore:
#      - '**.md'
on: [never]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Agrammon6
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      id: tests
      uses: oposs/raku-container-action@master
